package generator

import (
	"fmt"
	"go/format"
	"io"
	"strings"

	"github.com/dave/jennifer/jen"
)

func generateCode(w io.Writer, factories []factory, cfg Config) error {
	f := jen.NewFile(cfg.PkgName)
	f.HeaderComment("Code generated by gcce/wire. DO NOT EDIT.")

	rootType := typeStmt(cfg.RootType)

	params := externalsToParams(factories)
	body := make([]jen.Code, 0, len(factories)*3+1)

	var rootVar string

	hasError := false

	for _, fac := range factories {
		if fac.external {
			continue
		}

		if fac.root {
			rootVar = fac.varName
		}

		if fac.returnsErr {
			hasError = true
		}

		body = append(body, buildFactoryStmt(fac, cfg.RootType)...)
	}

	if hasError {
		body = append(body, jen.Return(jen.List(jen.Id(rootVar), jen.Nil())))
		f.Func().Id(cfg.FuncName).Params(params...).Params(rootType, jen.Error()).Block(body...)
	} else {
		body = append(body, jen.Return(jen.Id(rootVar)))
		f.Func().Id(cfg.FuncName).Params(params...).Params(rootType).Block(body...)
	}

	src, err := format.Source([]byte(f.GoString()))
	if err != nil {
		return fmt.Errorf("codegen: go fmt failed: %w\n\n%s", err, f.GoString())
	}

	_, err = w.Write(src)

	return err
}

func typeStmt(fqn string) *jen.Statement {
	isSlice := strings.HasPrefix(fqn, "[]")
	if isSlice {
		fqn = fqn[2:]
	}

	ptr := strings.HasPrefix(fqn, "*")
	if ptr {
		fqn = fqn[1:]
	}

	lastDot := strings.LastIndex(fqn, ".")

	var stmt *jen.Statement
	if lastDot < 0 {
		stmt = jen.Id(fqn)
	} else {
		stmt = jen.Qual(fqn[:lastDot], fqn[lastDot+1:])
	}

	if ptr {
		stmt = jen.Op("*").Add(stmt)
	}

	if isSlice {
		stmt = jen.Index().Add(stmt)
	}

	return stmt
}

func callStmt(fqn string) *jen.Statement {
	lastDot := strings.LastIndex(fqn, ".")
	if lastDot < 0 {
		return jen.Id(fqn)
	}

	return jen.Qual(fqn[:lastDot], fqn[lastDot+1:])
}

func externalsToParams(factories []factory) []jen.Code {
	params := make([]jen.Code, 0)

	for _, fac := range factories {
		if fac.external {
			params = append(params, jen.Id(fac.varName).Add(typeStmt(fac.target)))
		}
	}

	return params
}

func buildFactoryStmt(fac factory, rootType string) []jen.Code {
	ctor := callStmt(fac.ctor)
	args := make([]jen.Code, len(fac.ctorArgs))

	for i, a := range fac.ctorArgs {
		if fac.variadic && i == len(fac.ctorArgs)-1 {
			args[i] = jen.Add(jen.Id(a), jen.Op("..."))
		} else {
			args[i] = jen.Id(a)
		}
	}

	if !fac.returnsErr {
		return []jen.Code{jen.Id(fac.varName).Op(":=").Add(ctor).Call(args...)}
	}

	returnNil := jen.Nil()
	if !strings.HasPrefix(rootType, "*") {
		returnNil = jen.Op("*").Add(jen.New(typeStmt(rootType)))
	}

	return []jen.Code{
		jen.List(jen.Id(fac.varName), jen.Err()).Op(":=").Add(ctor).Call(args...),
		jen.If(jen.Err().Op("!=").Nil()).Block(
			jen.Return(jen.List(returnNil, jen.Err())),
		),
	}
}
