// Code generated by thumbrise/pipass; DO NOT EDIT.

package pass

import (
	schema "github.com/thumbrise/op-universal-schema-go/schema"
	pipass "github.com/thumbrise/pipass"
	"go/ast"
	"reflect"
	"strconv"
)

type InstructionPass interface {
	ID() string
	SetID(value string, reason string)
	Comment() string
	SetComment(value string, reason string)
	Version() string
	SetVersion(value string, reason string)
	Operations() []OperationPass
	MapOperations(func(child OperationPass) error) error
	AppendOperations(value OperationPass, reason string)
	Trait() []TermPass
	MapTrait(func(child TermPass) error) error
	AppendTrait(value TermPass, reason string)
	Drop(reason string)
	Dropped() bool
	Undrop(reason string)
}
type InstructionPipePass struct {
	_path      string
	_ledger    pipass.Ledger
	_dropped   bool
	iD         string
	comment    string
	version    string
	operations []*OperationPipePass
	trait      []*TermPipePass
}

func NewInstructionPipePass(path string, ledger pipass.Ledger) *InstructionPipePass {
	return &InstructionPipePass{
		_ledger: ledger,
		_path:   path,
	}
}
func (p *InstructionPipePass) ID() string {
	return p.iD
}
func (p *InstructionPipePass) SetID(value string, reason string) {
	if reflect.DeepEqual(p.iD, value) {
		return
	}
	prev := p.iD
	p.iD = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".ID", reason, prev, value)
	}
}
func (p *InstructionPipePass) Comment() string {
	return p.comment
}
func (p *InstructionPipePass) SetComment(value string, reason string) {
	if reflect.DeepEqual(p.comment, value) {
		return
	}
	prev := p.comment
	p.comment = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Comment", reason, prev, value)
	}
}
func (p *InstructionPipePass) Version() string {
	return p.version
}
func (p *InstructionPipePass) SetVersion(value string, reason string) {
	if reflect.DeepEqual(p.version, value) {
		return
	}
	prev := p.version
	p.version = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Version", reason, prev, value)
	}
}
func (p *InstructionPipePass) Operations() []OperationPass {
	if p.operations == nil {
		return nil
	}
	res := make([]OperationPass, len(p.operations))
	for i := 0; i < len(p.operations); i++ {
		res[i] = p.operations[i]
	}
	return res
}
func (p *InstructionPipePass) MapOperations(fn func(child OperationPass) error) error {
	if p.operations == nil {
		p.operations = []*OperationPipePass{}
	}
	for i := 0; i < len(p.operations); i++ {
		childPath := p._path + ".Operations[" + strconv.Itoa(i) + "]"
		childPass := p.operations[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *InstructionPipePass) AppendOperations(value OperationPass, reason string) {
	if p.operations == nil {
		p.operations = []*OperationPipePass{}
	}
	concreteChild, ok := value.(*OperationPipePass)
	if ok && concreteChild != nil {
		p.operations = append(p.operations, concreteChild)
		idx := len(p.operations) - 1
		childPath := p._path + ".Operations[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *InstructionPipePass) Trait() []TermPass {
	if p.trait == nil {
		return nil
	}
	res := make([]TermPass, len(p.trait))
	for i := 0; i < len(p.trait); i++ {
		res[i] = p.trait[i]
	}
	return res
}
func (p *InstructionPipePass) MapTrait(fn func(child TermPass) error) error {
	if p.trait == nil {
		p.trait = []*TermPipePass{}
	}
	for i := 0; i < len(p.trait); i++ {
		childPath := p._path + ".Trait[" + strconv.Itoa(i) + "]"
		childPass := p.trait[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *InstructionPipePass) AppendTrait(value TermPass, reason string) {
	if p.trait == nil {
		p.trait = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.trait = append(p.trait, concreteChild)
		idx := len(p.trait) - 1
		childPath := p._path + ".Trait[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *InstructionPipePass) Drop(reason string) {
	if p._dropped {
		return
	}
	p._dropped = true
	if p._ledger != nil {
		p._ledger.Log(p._path, reason, p, nil)
	}
}
func (p *InstructionPipePass) Dropped() bool {
	return p._dropped
}
func (p *InstructionPipePass) Undrop(reason string) {
	if !p._dropped {
		return
	}
	p._dropped = false
	if p._ledger != nil {
		p._ledger.Log(p._path, reason, nil, p)
	}
}

type TermPass interface {
	ID() string
	SetID(value string, reason string)
	Comment() string
	SetComment(value string, reason string)
	Required() *bool
	SetRequired(value *bool, reason string)
	Kind() *schema.Kind
	SetKind(value *schema.Kind, reason string)
	Value() interface{}
	SetValue(value interface{}, reason string)
	Of() []TermPass
	MapOf(func(child TermPass) error) error
	AppendOf(value TermPass, reason string)
	Trait() []TermPass
	MapTrait(func(child TermPass) error) error
	AppendTrait(value TermPass, reason string)
	ReflectType() reflect.Type
	SetReflectType(value reflect.Type, reason string)
	Drop(reason string)
	Dropped() bool
	Undrop(reason string)
}
type TermPipePass struct {
	_path       string
	_ledger     pipass.Ledger
	_dropped    bool
	iD          string
	comment     string
	required    *bool
	kind        *schema.Kind
	value       interface{}
	of          []*TermPipePass
	trait       []*TermPipePass
	reflectType reflect.Type
}

func NewTermPipePass(path string, ledger pipass.Ledger) *TermPipePass {
	return &TermPipePass{
		_ledger: ledger,
		_path:   path,
	}
}
func (p *TermPipePass) ID() string {
	return p.iD
}
func (p *TermPipePass) SetID(value string, reason string) {
	if reflect.DeepEqual(p.iD, value) {
		return
	}
	prev := p.iD
	p.iD = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".ID", reason, prev, value)
	}
}
func (p *TermPipePass) Comment() string {
	return p.comment
}
func (p *TermPipePass) SetComment(value string, reason string) {
	if reflect.DeepEqual(p.comment, value) {
		return
	}
	prev := p.comment
	p.comment = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Comment", reason, prev, value)
	}
}
func (p *TermPipePass) Required() *bool {
	return p.required
}
func (p *TermPipePass) SetRequired(value *bool, reason string) {
	if reflect.DeepEqual(p.required, value) {
		return
	}
	prev := p.required
	p.required = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Required", reason, prev, value)
	}
}
func (p *TermPipePass) Kind() *schema.Kind {
	return p.kind
}
func (p *TermPipePass) SetKind(value *schema.Kind, reason string) {
	if reflect.DeepEqual(p.kind, value) {
		return
	}
	prev := p.kind
	p.kind = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Kind", reason, prev, value)
	}
}
func (p *TermPipePass) Value() interface{} {
	return p.value
}
func (p *TermPipePass) SetValue(value interface{}, reason string) {
	if reflect.DeepEqual(p.value, value) {
		return
	}
	prev := p.value
	p.value = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Value", reason, prev, value)
	}
}
func (p *TermPipePass) Of() []TermPass {
	if p.of == nil {
		return nil
	}
	res := make([]TermPass, len(p.of))
	for i := 0; i < len(p.of); i++ {
		res[i] = p.of[i]
	}
	return res
}
func (p *TermPipePass) MapOf(fn func(child TermPass) error) error {
	if p.of == nil {
		p.of = []*TermPipePass{}
	}
	for i := 0; i < len(p.of); i++ {
		childPath := p._path + ".Of[" + strconv.Itoa(i) + "]"
		childPass := p.of[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *TermPipePass) AppendOf(value TermPass, reason string) {
	if p.of == nil {
		p.of = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.of = append(p.of, concreteChild)
		idx := len(p.of) - 1
		childPath := p._path + ".Of[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *TermPipePass) Trait() []TermPass {
	if p.trait == nil {
		return nil
	}
	res := make([]TermPass, len(p.trait))
	for i := 0; i < len(p.trait); i++ {
		res[i] = p.trait[i]
	}
	return res
}
func (p *TermPipePass) MapTrait(fn func(child TermPass) error) error {
	if p.trait == nil {
		p.trait = []*TermPipePass{}
	}
	for i := 0; i < len(p.trait); i++ {
		childPath := p._path + ".Trait[" + strconv.Itoa(i) + "]"
		childPass := p.trait[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *TermPipePass) AppendTrait(value TermPass, reason string) {
	if p.trait == nil {
		p.trait = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.trait = append(p.trait, concreteChild)
		idx := len(p.trait) - 1
		childPath := p._path + ".Trait[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *TermPipePass) ReflectType() reflect.Type {
	return p.reflectType
}
func (p *TermPipePass) SetReflectType(value reflect.Type, reason string) {
	if reflect.DeepEqual(p.reflectType, value) {
		return
	}
	prev := p.reflectType
	p.reflectType = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".ReflectType", reason, prev, value)
	}
}
func (p *TermPipePass) Drop(reason string) {
	if p._dropped {
		return
	}
	p._dropped = true
	if p._ledger != nil {
		p._ledger.Log(p._path, reason, p, nil)
	}
}
func (p *TermPipePass) Dropped() bool {
	return p._dropped
}
func (p *TermPipePass) Undrop(reason string) {
	if !p._dropped {
		return
	}
	p._dropped = false
	if p._ledger != nil {
		p._ledger.Log(p._path, reason, nil, p)
	}
}

type OperationPass interface {
	ID() string
	SetID(value string, reason string)
	Comment() string
	SetComment(value string, reason string)
	Input() []TermPass
	MapInput(func(child TermPass) error) error
	AppendInput(value TermPass, reason string)
	Output() []TermPass
	MapOutput(func(child TermPass) error) error
	AppendOutput(value TermPass, reason string)
	Error() []TermPass
	MapError(func(child TermPass) error) error
	AppendError(value TermPass, reason string)
	Trait() []TermPass
	MapTrait(func(child TermPass) error) error
	AppendTrait(value TermPass, reason string)
	ReflectType() reflect.Type
	SetReflectType(value reflect.Type, reason string)
	ASTFuncDecl() *ast.FuncDecl
	SetASTFuncDecl(value *ast.FuncDecl, reason string)
	Drop(reason string)
	Dropped() bool
	Undrop(reason string)
}
type OperationPipePass struct {
	_path       string
	_ledger     pipass.Ledger
	_dropped    bool
	iD          string
	comment     string
	input       []*TermPipePass
	output      []*TermPipePass
	error       []*TermPipePass
	trait       []*TermPipePass
	reflectType reflect.Type
	aSTFuncDecl *ast.FuncDecl
}

func NewOperationPipePass(path string, ledger pipass.Ledger) *OperationPipePass {
	return &OperationPipePass{
		_ledger: ledger,
		_path:   path,
	}
}
func (p *OperationPipePass) ID() string {
	return p.iD
}
func (p *OperationPipePass) SetID(value string, reason string) {
	if reflect.DeepEqual(p.iD, value) {
		return
	}
	prev := p.iD
	p.iD = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".ID", reason, prev, value)
	}
}
func (p *OperationPipePass) Comment() string {
	return p.comment
}
func (p *OperationPipePass) SetComment(value string, reason string) {
	if reflect.DeepEqual(p.comment, value) {
		return
	}
	prev := p.comment
	p.comment = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".Comment", reason, prev, value)
	}
}
func (p *OperationPipePass) Input() []TermPass {
	if p.input == nil {
		return nil
	}
	res := make([]TermPass, len(p.input))
	for i := 0; i < len(p.input); i++ {
		res[i] = p.input[i]
	}
	return res
}
func (p *OperationPipePass) MapInput(fn func(child TermPass) error) error {
	if p.input == nil {
		p.input = []*TermPipePass{}
	}
	for i := 0; i < len(p.input); i++ {
		childPath := p._path + ".Input[" + strconv.Itoa(i) + "]"
		childPass := p.input[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *OperationPipePass) AppendInput(value TermPass, reason string) {
	if p.input == nil {
		p.input = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.input = append(p.input, concreteChild)
		idx := len(p.input) - 1
		childPath := p._path + ".Input[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *OperationPipePass) Output() []TermPass {
	if p.output == nil {
		return nil
	}
	res := make([]TermPass, len(p.output))
	for i := 0; i < len(p.output); i++ {
		res[i] = p.output[i]
	}
	return res
}
func (p *OperationPipePass) MapOutput(fn func(child TermPass) error) error {
	if p.output == nil {
		p.output = []*TermPipePass{}
	}
	for i := 0; i < len(p.output); i++ {
		childPath := p._path + ".Output[" + strconv.Itoa(i) + "]"
		childPass := p.output[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *OperationPipePass) AppendOutput(value TermPass, reason string) {
	if p.output == nil {
		p.output = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.output = append(p.output, concreteChild)
		idx := len(p.output) - 1
		childPath := p._path + ".Output[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *OperationPipePass) Error() []TermPass {
	if p.error == nil {
		return nil
	}
	res := make([]TermPass, len(p.error))
	for i := 0; i < len(p.error); i++ {
		res[i] = p.error[i]
	}
	return res
}
func (p *OperationPipePass) MapError(fn func(child TermPass) error) error {
	if p.error == nil {
		p.error = []*TermPipePass{}
	}
	for i := 0; i < len(p.error); i++ {
		childPath := p._path + ".Error[" + strconv.Itoa(i) + "]"
		childPass := p.error[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *OperationPipePass) AppendError(value TermPass, reason string) {
	if p.error == nil {
		p.error = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.error = append(p.error, concreteChild)
		idx := len(p.error) - 1
		childPath := p._path + ".Error[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *OperationPipePass) Trait() []TermPass {
	if p.trait == nil {
		return nil
	}
	res := make([]TermPass, len(p.trait))
	for i := 0; i < len(p.trait); i++ {
		res[i] = p.trait[i]
	}
	return res
}
func (p *OperationPipePass) MapTrait(fn func(child TermPass) error) error {
	if p.trait == nil {
		p.trait = []*TermPipePass{}
	}
	for i := 0; i < len(p.trait); i++ {
		childPath := p._path + ".Trait[" + strconv.Itoa(i) + "]"
		childPass := p.trait[i]
		childPass._path = childPath
		childPass._ledger = p._ledger
		if err := fn(childPass); err != nil {
			return err
		}
	}
	return nil
}
func (p *OperationPipePass) AppendTrait(value TermPass, reason string) {
	if p.trait == nil {
		p.trait = []*TermPipePass{}
	}
	concreteChild, ok := value.(*TermPipePass)
	if ok && concreteChild != nil {
		p.trait = append(p.trait, concreteChild)
		idx := len(p.trait) - 1
		childPath := p._path + ".Trait[" + strconv.Itoa(idx) + "]"
		concreteChild._path = childPath
		concreteChild._ledger = p._ledger
		if p._ledger != nil {
			p._ledger.Log(childPath, reason, nil, concreteChild)
		}
	}
}
func (p *OperationPipePass) ReflectType() reflect.Type {
	return p.reflectType
}
func (p *OperationPipePass) SetReflectType(value reflect.Type, reason string) {
	if reflect.DeepEqual(p.reflectType, value) {
		return
	}
	prev := p.reflectType
	p.reflectType = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".ReflectType", reason, prev, value)
	}
}
func (p *OperationPipePass) ASTFuncDecl() *ast.FuncDecl {
	return p.aSTFuncDecl
}
func (p *OperationPipePass) SetASTFuncDecl(value *ast.FuncDecl, reason string) {
	if reflect.DeepEqual(p.aSTFuncDecl, value) {
		return
	}
	prev := p.aSTFuncDecl
	p.aSTFuncDecl = value
	if p._ledger != nil {
		p._ledger.Log(p._path+".ASTFuncDecl", reason, prev, value)
	}
}
func (p *OperationPipePass) Drop(reason string) {
	if p._dropped {
		return
	}
	p._dropped = true
	if p._ledger != nil {
		p._ledger.Log(p._path, reason, p, nil)
	}
}
func (p *OperationPipePass) Dropped() bool {
	return p._dropped
}
func (p *OperationPipePass) Undrop(reason string) {
	if !p._dropped {
		return
	}
	p._dropped = false
	if p._ledger != nil {
		p._ledger.Log(p._path, reason, nil, p)
	}
}
