package wire

import (
	"fmt"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/thumbrise/gcce/composition"
)

func typeNameForFunc(typeStr string) string {
	name := strings.TrimLeft(typeStr, "*")
	if lastDot := strings.LastIndex(name, "."); lastDot >= 0 {
		name = name[lastDot+1:]
	}

	return name
}

func typeExpr(ct composition.CompileType) *jen.Statement {
	s := new(jen.Statement)
	typeStr := ct.Type

	i := 0
	for i < len(typeStr) {
		if i+1 < len(typeStr) && typeStr[i] == '[' && typeStr[i+1] == ']' {
			s = s.Index()
			i += 2

			continue
		}

		if typeStr[i] == '*' {
			s = s.Op("*")
			i++

			continue
		}

		break
	}

	baseType := typeStr[i:]

	var typeName string
	if lastDot := strings.LastIndex(baseType, "."); lastDot >= 0 {
		typeName = baseType[lastDot+1:]
	} else {
		typeName = baseType
	}

	if ct.ImportPath != "" {
		s = s.Qual(ct.ImportPath, typeName)
	} else {
		s = s.Id(typeName)
	}

	return s
}

func generate(steps []composition.GraphStep, cfg *config) (string, error) {
	rootIdx, typeMap := buildIndex(steps, cfg.rootType.String())
	switch {
	case rootIdx < -1:
		return "", fmt.Errorf("%w: %s", ErrMultipleRoots, cfg.rootType.String())
	case rootIdx < 0:
		return "", fmt.Errorf("%w: %s", ErrRootNotFound, cfg.rootType.String())
	}

	returnsErr := steps[rootIdx].ReturnsErr
	if !returnsErr {
		for _, s := range steps[:rootIdx] {
			if s.ReturnsErr {
				return "", fmt.Errorf("%w: step producing %s", ErrStepReturnsError, s.TargetType.Type)
			}
		}
	}

	f := jen.NewFile(cfg.packageName)
	f.HeaderComment("Code generated by gcce/ecosystem/wire. DO NOT EDIT.")

	vars := map[int]string{}

	body, err := buildBody(steps, rootIdx, returnsErr, typeMap, vars)
	if err != nil {
		return "", err
	}

	if returnsErr {
		f.Func().Id(cfg.functionName).Params().Params(
			typeExpr(steps[rootIdx].TargetType), jen.Error(),
		).Block(body...)
	} else {
		f.Func().Id(cfg.functionName).Params().Params(
			typeExpr(steps[rootIdx].TargetType),
		).Block(body...)
	}

	return f.GoString(), nil
}

func buildBody(steps []composition.GraphStep, rootIdx int, returnsErr bool, typeMap map[string][]int, vars map[int]string) ([]jen.Code, error) {
	var body []jen.Code

	for idx := 0; idx <= rootIdx; idx++ {
		s := steps[idx]
		vname := fmt.Sprintf("_v%d", idx)
		vars[idx] = vname

		if s.FuncName == "" && s.PackagePath == "" {
			continue
		}

		args := make([]jen.Code, len(s.ArgsTypes))
		for ai, argType := range s.ArgsTypes {
			arg, err := resolveArg(argType, typeMap, vars, idx)
			if err != nil {
				return nil, fmt.Errorf("step %d (%s): %w", idx, s.TargetType.Type, err)
			}

			args[ai] = arg
		}

		var call *jen.Statement
		if s.PackagePath != "" {
			call = jen.Qual(s.PackagePath, s.FuncName).Call(args...)
		} else {
			call = jen.Id(s.FuncName).Call(args...)
		}

		if s.ReturnsErr {
			body = append(body, jen.List(jen.Id(vname), jen.Err()).Op(":=").Add(call))
			body = append(body, jen.If(jen.Err().Op("!=").Nil()).Block(
				jen.Var().Id("_zero").Add(typeExpr(steps[rootIdx].TargetType)),
				jen.Return(jen.Id("_zero"), jen.Err()),
			))
		} else {
			body = append(body, jen.Id(vname).Op(":=").Add(call))
		}
	}

	lastVar := vars[rootIdx]
	if returnsErr {
		body = append(body, jen.Return(jen.Id(lastVar), jen.Nil()))
	} else {
		body = append(body, jen.Return(jen.Id(lastVar)))
	}

	return body, nil
}

func buildIndex(steps []composition.GraphStep, rootStr string) (int, map[string][]int) {
	rootIdx := -1
	typeMap := map[string][]int{}

	for i, s := range steps {
		typeMap[s.TargetType.Type] = append(typeMap[s.TargetType.Type], i)
		if s.TargetType.Type == rootStr {
			if rootIdx >= 0 {
				return -2, typeMap
			}

			rootIdx = i
		}
	}

	return rootIdx, typeMap
}
